import logging

logging.basicConfig( format = '%(filename)s  %(levelname)-10s  %(message)s'
                     , level=logging.INFO)


G_CONST_DEFINE_FILE = 'C:/bobyan/project/Stock/Shanghai.xlsx'


G_CONST_DB_SERVER = "127.0.0.1"
G_CONST_DB_INSTANCE_NAME = "STOCK"
G_CONST_DB_DETAIL_TABLE = "history_table"
G_CONST_DB_PORT = 27017    
G_CONST_DB_INFO_TABLE = "introduction_table"

G_CONST_YAHOO_HISTORY_CSV_URL = "http://table.finance.yahoo.com/table.csv?s="
G_CONST_SOHU_HISTORY_CSV_URL = "http://q.stock.sohu.com/hisHq?code="



G_CONST_DATE_FIELD_NAME = "timestamp"
G_CONST_ID_FIELD_NAME = "_id"
G_CONST_VOLUMN_FIELD_NAME = "Volume"
G_CONST_TURNOVER_FIELD_NAME = "Turnover"
G_CONST_EXCHANGE_RATE_FIELD_NAME = "ExchangeRate"
G_CONST_ClOSE_FIELD_NAME = "Close"
G_CONST_HIGH_FIELD_NAME = "High"
G_CONST_LOW_FIELD_NAME = "Low"
G_CONST_CHANCE_CLOSE_FIELD_NAME = "ChangeValue"
G_CONST_ADJ_RATE_FIELD_NAME = "adj_ratio"
G_CONST_ADJ_CLOSE_FIELD_NAME = "Adj Close"
G_CONST_OPEN_FIELD_NAME = "Open"
G_CONST_DAILY_RATIO_FIELD_NAME = "daily_ratio"
G_CONST_WEEK_RATIO_FIELD_NAME = "weekly_ratio"
G_CONST_MONTH_RATIO_FIELD_NAME = "month_ratio"
G_CONST_QUATER_RATIO_FIELD_NAME = "quater_ratio"
G_CONST_5DAY_AVG_FIELD_NAME = "five_days_average"
G_CONST_10DAY_AVG_FIELD_NAME = "ten_days_average"
G_CONST_20DAY_AVG_FIELD_NAME = "twenty_days_average"

G_CONST_5DAY_AVG_COUNT = 5
G_CONST_10DAY_AVG_COUNT  = 10
G_CONST_20DAY_AVG_COUNT  = 20


G_CONST_CALCULATION_RSV_NAME = "INDEX_RSV"
G_CONST_CALCULATION_K_NAME = "INDEX_K"
G_CONST_CALCULATION_D_NAME = "INDEX_D"
G_CONST_CALCULATION_J_NAME = "INDEX_J"


G_CONST_CALCULATION_MACD_SHORT_NAME = "MACD_EMA_SHORT"
G_CONST_CALCULATION_MACD_LONG_NAME = "MACD_EMA_LONG"
G_CONST_CALCULATION_MACD_DIFF_NAME = "MACD_DIFF"
G_CONST_CALCULATION_MACD_DEA_NAME = "MACD_DEA"
G_CONST_CALCULATION_MACD_BAR_NAME = "MACD_BAR"
G_CONST_CALCULATION_MACD_12_NAME = "INDEX_MACD_12"
G_CONST_CALCULATION_MACD_12_NAME = "INDEX_MACD_26"

G_CONST_CALCULATION_RSI_6_NAME = "INDEX_RSI_6"
G_CONST_CALCULATION_RSI_12_NAME = "INDEX_RSI_12"
G_CONST_CALCULATION_RSI_24_NAME = "INDEX_RSI_24"
G_CONST_CALCULATION_RSI_UP_NAME = "INDEX_RSI_UP"
G_CONST_CALCULATION_RSI_DOWN_NAME = "INDEX_RSI_DOWN"
G_CONST_CALCULATION_RSI_SIMPLE_UP_NAME = "INDEX_SIMPLE_UP"
G_CONST_CALCULATION_RSI_SIMPLE_DOWN_NAME = "INDEX_SIMPLE_DOWN"


G_CONST_CALCULATION_BOLL_MA = "INDEX_BOLL_MA"
G_CONST_CALCULATION_BOLL_MD = "INDEX_BOLL_MD"
G_CONST_CALCULATION_BOLL_MA_MD = "INDEX_BOLL_MA_MD"
G_CONST_CALCULATION_BOLL_UP = "INDEX_BOLL_UP"
G_CONST_CALCULATION_BOLL_DOWN = "INDEX_BOLL_DOWN"

G_CONST_START_TIME = "1999-10-11"
#G_CONST_START_TIME = "2016-01-04"
G_CONST_TIME_FORMATE = "%Y-%m-%d"

G_CONST_STUDY_CORRECT = "IS_CORRECT"
G_CONST_STUDY_GOOD_VALUE = "GOOD_VALUE"
G_CONST_STUDY_INFO = "STUDY_INFO"
G_CONST_STUDY_REAL_RATE = "REAL_RATE"
G_CONST_STUDY_DEAL_DAYS = "RELATIVE_DAYS"
G_CONST_STUDY_DEAL_DATE = "DEAL_DATE"
G_CONST_STUDY_DEAL_START_VALUE = "DEAL_START_VALUE"
G_CONST_STUDY_DEAL_END_VALUE = "DEAL_END_VALUE"
G_CONST_STUDY_EXPECTED_RATE = 0.5

